export const COOKIE_KEYS = {
  IS_REGISTERED: "IS_REGISTERED",
  TOKEN: "TOKEN",
  REFRESH_TOKEN: "REFRESH_TOKEN",
  ONBOARDING: "ONBOARDING",
  PUSH_NOTIFY: "PUSH_NOTIFY",
};

export const querykeys = {
  INCIDENT_TICKET: "INCIDENT_TICKET",
};
