name: Continuous Integration

on:
  # push:
  #   branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  NODE_VERSION: 20.14.0
  PNPM_VERSION: 10.8.1 
  CI: true

jobs:
  lint:
    name: Lint and Typecheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install pnpm
        if: env.PNPM_VERSION
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Typecheck
        run: pnpm typecheck

      - name: Run ESLint
        run: pnpm lint

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint

    steps:  
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          
      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run:  pnpm install --frozen-lockfile
      - name: Install pnpm
      - name: Verify pnpm installation
        run: pnpm --version
        
      - name: Run tests
        run: pnpm test
        env:
          CI: true

  build:
    name: Verify Build
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install pnpm
        if: env.PNPM_VERSION
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build application
        run: pnpm build

      - name: Run security audit
        run: pnpm audit
